-- MySQL Script generated by MySQL Workbench
-- 04/09/18 22:22:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Categoria` (
  `idCategoria` VARCHAR(2) NOT NULL,
  `Salario` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Emp` (
  `idEmpregado` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(80) NOT NULL DEFAULT 0,
  `Categoria_idCategoria` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idEmpregado`, `Categoria_idCategoria`),
  INDEX `fk_Empregado_Categoria_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Empregado_Categoria`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proj` (
  `idProjeto` VARCHAR(6) NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `Descricao` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idProjeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_Emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_Emp` (
  `Projeto_idProjeto` VARCHAR(6) NOT NULL,
  `Empregado_idEmpregado` INT NOT NULL,
  `Empregado_Categoria_idCategoria` VARCHAR(2) NOT NULL,
  `Data_Inicial` DATE NULL,
  `TempoAI` INT(2) NULL,
  PRIMARY KEY (`Projeto_idProjeto`, `Empregado_idEmpregado`, `Empregado_Categoria_idCategoria`),
  INDEX `fk_Projeto_has_Empregado_Empregado1_idx` (`Empregado_idEmpregado` ASC, `Empregado_Categoria_idCategoria` ASC),
  INDEX `fk_Projeto_has_Empregado_Projeto1_idx` (`Projeto_idProjeto` ASC),
  CONSTRAINT `fk_Projeto_has_Empregado_Projeto1`
    FOREIGN KEY (`Projeto_idProjeto`)
    REFERENCES `Proj` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_has_Empregado_Empregado1`
    FOREIGN KEY (`Empregado_idEmpregado` , `Empregado_Categoria_idCategoria`)
    REFERENCES `Emp` (`idEmpregado` , `Categoria_idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
