-- MySQL Script generated by MySQL Workbench
-- 04/16/18 22:28:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nomeCurso` VARCHAR(45) NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Usuário` (
  `idUsuário` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuário` VARCHAR(80) NOT NULL,
  `foneUsuário` INT NULL,
  `emailUsuário` VARCHAR(120) NULL,
  `RAUsuário` INT NULL,
  `senhaUsuário` VARCHAR(45) NULL,
  `cursoUsuário` VARCHAR(45) NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idUsuário`),
  UNIQUE INDEX `emailUsuário_UNIQUE` (`emailUsuário` ASC),
  INDEX `fk_Usuário_Curso1_idx` (`Curso_idCurso` ASC),
  CONSTRAINT `fk_Usuário_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Livro` (
  `idLivro` INT NOT NULL AUTO_INCREMENT,
  `nomeLivro` VARCHAR(45) NULL,
  `ISBN` INT NULL,
  `ano_publicacaoLivro` VARCHAR(45) NULL,
  `edicaoLivro` VARCHAR(45) NULL,
  `autorLivro` VARCHAR(45) NULL,
  PRIMARY KEY (`idLivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `nomeAutor` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Emprestimo` (
  `idEmprestimo` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL,
  `data_devolucaoEmprestimo` DATE NULL,
  `atrasadoEmprestimo` TINYINT(1) NULL,
  `Usuário_idUsuário` INT NOT NULL,
  `data_prevista` DATE NOT NULL,
  `Livro_idLivro` INT NOT NULL,
  PRIMARY KEY (`idEmprestimo`),
  INDEX `fk_Emprestimo_Usuário1_idx` (`Usuário_idUsuário` ASC),
  INDEX `fk_Emprestimo_Livro1_idx` (`Livro_idLivro` ASC),
  CONSTRAINT `fk_Emprestimo_Usuário1`
    FOREIGN KEY (`Usuário_idUsuário`)
    REFERENCES `Usuário` (`idUsuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emprestimo_Livro1`
    FOREIGN KEY (`Livro_idLivro`)
    REFERENCES `Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Atendente` (
  `idAtendente` INT NOT NULL AUTO_INCREMENT,
  `nomeAtendente` VARCHAR(45) NULL,
  `emailAtendente` VARCHAR(45) NULL,
  `Emprestimo_idEmprestimo` INT NOT NULL,
  PRIMARY KEY (`idAtendente`),
  INDEX `fk_Atendente_Emprestimo1_idx` (`Emprestimo_idEmprestimo` ASC),
  CONSTRAINT `fk_Atendente_Emprestimo1`
    FOREIGN KEY (`Emprestimo_idEmprestimo`)
    REFERENCES `Emprestimo` (`idEmprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livro_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Livro_Autor` (
  `Livro_idLivro` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`Livro_idLivro`, `Autor_idAutor`),
  INDEX `fk_Livro_has_Autor_Autor1_idx` (`Autor_idAutor` ASC),
  INDEX `fk_Livro_has_Autor_Livro1_idx` (`Livro_idLivro` ASC),
  CONSTRAINT `fk_Livro_has_Autor_Livro1`
    FOREIGN KEY (`Livro_idLivro`)
    REFERENCES `Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
