-- MySQL Script generated by MySQL Workbench
-- Sun Apr 22 18:42:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Cliente_Fisico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cliente_Fisico` (
  `idCliente_Fisico` INT NOT NULL,
  `sexoCliente_Fisico` VARCHAR(1) NOT NULL,
  `nascimentoCliente_Fisico` DATE NULL,
  `enderecoCliente_Fisico` VARCHAR(45) NULL,
  `CPFCliente_Fisico` INT NOT NULL,
  `tel_residencialCliente_Fisico` INT NULL,
  `tel_celularCliente_Fisico` INT NULL,
  `tel_comercialCliente_Fisico` INT NULL,
  PRIMARY KEY (`idCliente_Fisico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cliente_Juridico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cliente_Juridico` (
  `idCliente_Juridico` INT NOT NULL,
  `nomeCliente_Juridico` VARCHAR(45) NOT NULL,
  `CNPJCliente_Juridico` INT NOT NULL,
  `enderecoCliente_Juridico` VARCHAR(45) NOT NULL,
  `tel_comercialCliente_Juridico` INT NOT NULL,
  PRIMARY KEY (`idCliente_Juridico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veiculo_Passeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Veiculo_Passeio` (
  `placaVeiculo_Passeio` VARCHAR(7) NOT NULL,
  `no_chasseiVeiculo_Passeio` INT NOT NULL,
  `corVeiculo_Passeio` VARCHAR(10) NOT NULL,
  `no_passageirosVeiculo_Passeio` INT NOT NULL,
  `ano_fabricacaoVeiculo_Passeio` DATE NULL,
  PRIMARY KEY (`placaVeiculo_Passeio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veiculo_Carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Veiculo_Carga` (
  `placaVeiculo_Carga` VARCHAR(7) NOT NULL,
  `no_chassiVeiculo_Carga` INT NOT NULL,
  `no_passegeirosVeiculo_Carga` INT NOT NULL,
  `ano_fabricacaoVeiculo_Carga` DATE NOT NULL,
  `capacidade_maximaVeiculo_Carga` DOUBLE NOT NULL,
  PRIMARY KEY (`placaVeiculo_Carga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habilitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habilitacao` (
  `no_Habilitacao` INT NOT NULL,
  `dataVencimentoHabilitacao` DATE NOT NULL,
  PRIMARY KEY (`no_Habilitacao`),
  UNIQUE INDEX `dataVencimentoHabilitacao_UNIQUE` (`dataVencimentoHabilitacao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Motorista` (
  `idMotorista` INT NOT NULL,
  `Habilitacao_no_Habilitacao` INT NOT NULL,
  `Veiculo_Passeio_placaVeiculo_Passeio` VARCHAR(7) NOT NULL,
  `Veiculo_Carga_placaVeiculo_Carga` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`idMotorista`),
  INDEX `fk_Motorista_Habilitacao_idx` (`Habilitacao_no_Habilitacao` ASC),
  INDEX `fk_Motorista_Veiculo_Passeio1_idx` (`Veiculo_Passeio_placaVeiculo_Passeio` ASC),
  INDEX `fk_Motorista_Veiculo_Carga1_idx` (`Veiculo_Carga_placaVeiculo_Carga` ASC),
  CONSTRAINT `fk_Motorista_Habilitacao`
    FOREIGN KEY (`Habilitacao_no_Habilitacao`)
    REFERENCES `Habilitacao` (`no_Habilitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Motorista_Veiculo_Passeio1`
    FOREIGN KEY (`Veiculo_Passeio_placaVeiculo_Passeio`)
    REFERENCES `Veiculo_Passeio` (`placaVeiculo_Passeio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Motorista_Veiculo_Carga1`
    FOREIGN KEY (`Veiculo_Carga_placaVeiculo_Carga`)
    REFERENCES `Veiculo_Carga` (`placaVeiculo_Carga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Seguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Seguradora` (
  `Motorista_idMotorista` INT NOT NULL,
  INDEX `fk_Seguradora_Motorista1_idx` (`Motorista_idMotorista` ASC),
  CONSTRAINT `fk_Seguradora_Motorista1`
    FOREIGN KEY (`Motorista_idMotorista`)
    REFERENCES `Motorista` (`idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aluguel_CNPJ-CARGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aluguel_CNPJ-CARGA` (
  `Cliente_Juridico_idCliente_Juridico` INT NOT NULL,
  `Veiculo_Carga_placaVeiculo_Carga` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`Cliente_Juridico_idCliente_Juridico`, `Veiculo_Carga_placaVeiculo_Carga`),
  INDEX `fk_Cliente_Juridico_has_Veiculo_Carga_Veiculo_Carga1_idx` (`Veiculo_Carga_placaVeiculo_Carga` ASC),
  INDEX `fk_Cliente_Juridico_has_Veiculo_Carga_Cliente_Juridico1_idx` (`Cliente_Juridico_idCliente_Juridico` ASC),
  CONSTRAINT `fk_Cliente_Juridico_has_Veiculo_Carga_Cliente_Juridico1`
    FOREIGN KEY (`Cliente_Juridico_idCliente_Juridico`)
    REFERENCES `Cliente_Juridico` (`idCliente_Juridico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Juridico_has_Veiculo_Carga_Veiculo_Carga1`
    FOREIGN KEY (`Veiculo_Carga_placaVeiculo_Carga`)
    REFERENCES `Veiculo_Carga` (`placaVeiculo_Carga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aluguel_CNPJ-PASSEIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aluguel_CNPJ-PASSEIO` (
  `Cliente_Juridico_idCliente_Juridico` INT NOT NULL,
  `Veiculo_Passeio_placaVeiculo_Passeio` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`Cliente_Juridico_idCliente_Juridico`, `Veiculo_Passeio_placaVeiculo_Passeio`),
  INDEX `fk_Cliente_Juridico_has_Veiculo_Passeio_Veiculo_Passeio1_idx` (`Veiculo_Passeio_placaVeiculo_Passeio` ASC),
  INDEX `fk_Cliente_Juridico_has_Veiculo_Passeio_Cliente_Juridico1_idx` (`Cliente_Juridico_idCliente_Juridico` ASC),
  CONSTRAINT `fk_Cliente_Juridico_has_Veiculo_Passeio_Cliente_Juridico1`
    FOREIGN KEY (`Cliente_Juridico_idCliente_Juridico`)
    REFERENCES `Cliente_Juridico` (`idCliente_Juridico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Juridico_has_Veiculo_Passeio_Veiculo_Passeio1`
    FOREIGN KEY (`Veiculo_Passeio_placaVeiculo_Passeio`)
    REFERENCES `Veiculo_Passeio` (`placaVeiculo_Passeio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aluguel_CPF-CARGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aluguel_CPF-CARGA` (
  `Cliente_Fisico_idCliente_Fisico` INT NOT NULL,
  `Veiculo_Carga_placaVeiculo_Carga` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`Cliente_Fisico_idCliente_Fisico`, `Veiculo_Carga_placaVeiculo_Carga`),
  INDEX `fk_Cliente_Fisico_has_Veiculo_Carga_Veiculo_Carga1_idx` (`Veiculo_Carga_placaVeiculo_Carga` ASC),
  INDEX `fk_Cliente_Fisico_has_Veiculo_Carga_Cliente_Fisico1_idx` (`Cliente_Fisico_idCliente_Fisico` ASC),
  CONSTRAINT `fk_Cliente_Fisico_has_Veiculo_Carga_Cliente_Fisico1`
    FOREIGN KEY (`Cliente_Fisico_idCliente_Fisico`)
    REFERENCES `Cliente_Fisico` (`idCliente_Fisico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Fisico_has_Veiculo_Carga_Veiculo_Carga1`
    FOREIGN KEY (`Veiculo_Carga_placaVeiculo_Carga`)
    REFERENCES `Veiculo_Carga` (`placaVeiculo_Carga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aluguel_CPF-Passeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aluguel_CPF-Passeio` (
  `Cliente_Fisico_idCliente_Fisico` INT NOT NULL,
  `Veiculo_Passeio_placaVeiculo_Passeio` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`Cliente_Fisico_idCliente_Fisico`, `Veiculo_Passeio_placaVeiculo_Passeio`),
  INDEX `fk_Cliente_Fisico_has_Veiculo_Passeio_Veiculo_Passeio1_idx` (`Veiculo_Passeio_placaVeiculo_Passeio` ASC),
  INDEX `fk_Cliente_Fisico_has_Veiculo_Passeio_Cliente_Fisico1_idx` (`Cliente_Fisico_idCliente_Fisico` ASC),
  CONSTRAINT `fk_Cliente_Fisico_has_Veiculo_Passeio_Cliente_Fisico1`
    FOREIGN KEY (`Cliente_Fisico_idCliente_Fisico`)
    REFERENCES `Cliente_Fisico` (`idCliente_Fisico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Fisico_has_Veiculo_Passeio_Veiculo_Passeio1`
    FOREIGN KEY (`Veiculo_Passeio_placaVeiculo_Passeio`)
    REFERENCES `Veiculo_Passeio` (`placaVeiculo_Passeio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
